version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: schoolxr-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: schoolxr
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: schoolxr-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017/schoolxr?authSource=admin
      MODE: dev
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: schoolxr-client
    restart: unless-stopped
    ports:
      - "80:80"

volumes:
  mongo_data:
